"""empty message

Revision ID: 29afad260210
Revises: d3c9dd2be80a
Create Date: 2017-03-16 18:46:21.529000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29afad260210'
down_revision = 'd3c9dd2be80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battle_counters', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('battle_counters', 'amount')
    # ### end Alembic commands ###
