"""empty message

Revision ID: 3d6bc80c57f2
Revises: ddff8461f25e
Create Date: 2017-04-07 15:02:06.766000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6bc80c57f2'
down_revision = 'ddff8461f25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shiki_soul_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soul_id', sa.Integer(), nullable=True),
    sa.Column('shikigami_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shikigami_id'], ['shikigamis.id'], ),
    sa.ForeignKeyConstraint(['soul_id'], ['souls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shiki_soul_sets_id'), 'shiki_soul_sets', ['id'], unique=False)
    op.create_index(op.f('ix_shiki_soul_sets_shikigami_id'), 'shiki_soul_sets', ['shikigami_id'], unique=False)
    op.create_index(op.f('ix_shiki_soul_sets_soul_id'), 'shiki_soul_sets', ['soul_id'], unique=False)
    op.add_column(u'shikigamis', sa.Column('role', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'shikigamis', 'role')
    op.drop_index(op.f('ix_shiki_soul_sets_soul_id'), table_name='shiki_soul_sets')
    op.drop_index(op.f('ix_shiki_soul_sets_shikigami_id'), table_name='shiki_soul_sets')
    op.drop_index(op.f('ix_shiki_soul_sets_id'), table_name='shiki_soul_sets')
    op.drop_table('shiki_soul_sets')
    # ### end Alembic commands ###
