"""empty message

Revision ID: 5802e139d9ff
Revises: 
Create Date: 2017-03-16 10:58:58.195000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5802e139d9ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shikigamis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('rarity', sa.String(length=4), nullable=True),
    sa.Column('awaken_materials', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shikigamis_name'), 'shikigamis', ['name'], unique=True)
    op.create_table('souls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('attr_2_pieces', sa.String(length=64), nullable=True),
    sa.Column('attr_4_pieces', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('mission_type', sa.Integer(), nullable=True),
    sa.Column('stamina_cost', sa.Integer(), nullable=True),
    sa.Column('soul_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['soul_id'], ['souls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('shikigami_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shikigami_id'], ['shikigamis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('shikigami_id', sa.Integer(), nullable=True),
    sa.Column('group_leader', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['shikigami_id'], ['shikigamis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_counters_mission_id'), 'battle_counters', ['mission_id'], unique=False)
    op.create_index(op.f('ix_battle_counters_shikigami_id'), 'battle_counters', ['shikigami_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_battle_counters_shikigami_id'), table_name='battle_counters')
    op.drop_index(op.f('ix_battle_counters_mission_id'), table_name='battle_counters')
    op.drop_table('battle_counters')
    op.drop_table('reward_quests')
    op.drop_table('missions')
    op.drop_table('souls')
    op.drop_index(op.f('ix_shikigamis_name'), table_name='shikigamis')
    op.drop_table('shikigamis')
    # ### end Alembic commands ###
