"""empty message

Revision ID: a68b627000b6
Revises: 29afad260210
Create Date: 2017-03-23 23:26:09.493000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68b627000b6'
down_revision = '29afad260210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_battle_counters_id'), 'battle_counters', ['id'], unique=False)
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_index(op.f('ix_missions_name'), 'missions', ['name'], unique=False)
    op.create_index(op.f('ix_shikigamis_id'), 'shikigamis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shikigamis_id'), table_name='shikigamis')
    op.drop_index(op.f('ix_missions_name'), table_name='missions')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_index(op.f('ix_battle_counters_id'), table_name='battle_counters')
    # ### end Alembic commands ###
