"""empty message

Revision ID: ddff8461f25e
Revises: a68b627000b6
Create Date: 2017-03-24 17:59:59.560000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddff8461f25e'
down_revision = 'a68b627000b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battle_counters', sa.Column('stamina_cost', sa.Integer(), nullable=True))
    op.add_column('missions', sa.Column('mission_stamina_cost', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_index(op.f('ix_missions_name'), 'missions', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_missions_name'), table_name='missions')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_column('missions', 'mission_stamina_cost')
    op.drop_column('battle_counters', 'stamina_cost')
    # ### end Alembic commands ###
